# can create new miniconda/anaconda environment using
# conda env create -f environment.yml; conda activate qpowergrid
name: qpowergrid
channels:
  - defaults
  - conda-forge
dependencies:
  # classiq only runs up to 3.11, not 3.12
  - python==3.11 
  - matplotlib
  - numpy
  - ipykernel  # for jupyter notebooks
  - networkx  # for general graphs
  - pyvis   # conda-forge::
  - pytorch  # for GNN
  # to install classiq:
  - pip  # to install classiq
  - pip:
    - classiq  
  # or qiskit:
  - qiskit-terra  # conda-forge::