# can create new miniconda/anaconda environment using
# conda env create -f environment.yml; conda activate qpowergrid
name: qpowergrid
channels:
  - defaults
  - conda-forge
dependencies:
  # classiq only runs up to 3.11, not 3.12
  - python==3.11 
  - ipykernel  # for jupyter notebooks
  - matplotlib
  - plotly
  - numpy
# PANDAPOWER REQUIREMENTS
  - pandapower
  - pytest
  - scipy
  - pandas
  - packaging
  - tqdm
  - deepdiff
  - networkx  # for general graphs
  - numba
  - pandapower
# OTHERS
  - pyvis   # conda-forge::
  - pytorch  # for GNN
  # to install classiq:
  - pip  # to install classiq
  - pip:
    - classiq  
  # or qiskit:
  - qiskit-terra  # conda-forge::